version: 2
jobs:
  build:
    working_directory: ~/woocourt-fe

    docker:
      # specify the version you desire here
      - image: circleci/node:12.16.1

    steps:
      - checkout
      # Download and cache dependencies

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache



      - run:
          name: Install Angular CLI and dependencies
          command: |
            sudo npm i @angular/cli@9.1.11 > /dev/null
            npm install
