version: 2
jobs:
  build:
    working_directory: ~/woocourt-fe

    docker:
      # specify the version you desire here
      - image: circleci/node:12.16.1

    steps:
      - checkout
      # Download and cache dependencies

      - add_ssh_keys:
          fingerprints:
            - "0a:c5:80:f7:8c:41:45:1c:0f:73:70:37:0a:7a:63:e5"

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install Angular CLI
          command: |
            sudo npm i -g @angular/cli@ > /dev/null

      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: build dist artifacts
          command: |
            ng build --prod --base-href https://woocourt.github.io/woocourt-site/

      - run:
          name: push to github deployment repo
          command: |
            git config --global -l
            git config --global user.email ${GIT_EMAIL}
            git config --global user.name ${GIT_USER}
            git commit . -m "deployment"
            git remote add github-deploy https://github.com/woocourt/woocourt-site.git
            git push github-deploy master
